nix-community/go-nix

default.nix, devshell.toml, flake.lock, flake.nix, overlay.nix, shell.nix, tests/default.nix
This is still not working and got this error instead:
```
rizary@RizaryWin:~/numtide/go-nix$ nix develop --show-trace
error: --- TypeError -------------------------------------------------------- nix
at: (69:67) in file: /nix/store/n6k3sacy2qvygkpjy1d5g9bvnji943k3-source/lib/fixed-points.nix
68|   #
69|   extends = f: rattrs: self: let super = rattrs self; in super // f self super;
|                                                                   ^
70| 
attempt to call something which is not a function but a set
---------------------------------- show-trace -----------------------------------
trace: while evaluating 'extends'
at: (69:24) in file: /nix/store/n6k3sacy2qvygkpjy1d5g9bvnji943k3-source/lib/fixed-points.nix
68|   #
69|   extends = f: rattrs: self: let super = rattrs self; in …
```
=> setup dev environment with flake

src/nar/list_test.go
While running the tests, I realized this Println to the console. I replaced it with a test, checking for equality.
=> list_test: remove Println, add proper assert.Equal

src/nar/hesitant_reader.go, src/nar/serialize.go, src/nar/serialize_test.go
There's no guarantees on how many bytes the Read() method of an io.Reader will write.
We can't assume it to block until all bytes requested are there - it can
return before (especially if it's still receiving on the other side).
This adds a "hesitantReader", which behaves like this, a failing unit test, then switches serialize.go over to use io.ReadFull (which behaves like we want it to).
After all that is done, we switch over to encoding/binary instead of bitshifting manually to produce the (u)int64.
=> nar/serialize.go: fix reader

README.md, libstore/nar_info.go, nar/doc.go, nar/ls/doc.go, nar/ls/list.go, nar/ls/list_test.go, nar/narinfo/parser.go, nar/narinfo/test.go, nar/narinfo/types.go
See individual commits for details.
This provides some more documentation, moves some things to more intuitive locations (`nar/list*` -> `nar/ls/`, `libstore/nar_info*` -> `nar/narinfo`), and simplifies the .narfile parser.
=> nar: refactor

nixbase32/nixbase32.go
This makes the alphabet publicly available, so consumers of go-nix can
use it.
=> //nixbase32: expose alphabet

pkg/wire/bytes_reader.go, pkg/wire/read.go, pkg/wire/read_test.go
`pkg/wire` test additions and refactor spun out of https://github.com/numtide/go-nix/pull/25:
- 3ed3531 feat(pkg/wire/read_test.go): add ReadString tests
- aa2b6cd feat(pkg/wire/read_test.go): add ReadBytesFull test cases
- 802d8b5 feat(pkg/wire/read_test.go): add bool test cases
- 243c35e feat(pkg/wire): make ReadBytes return a io.ReadCloser, add ReadBytesFull function
- d431594 fix(pkg/wire): rename tests to read_test.go
=> pkg/wire: add more tests

pkg/wire/read_test.go, pkg/wire/write_test.go
This adds some tests for the `pkg/wire.Write*` functions.
Some of the magic bytes used in the read tests is moved to global variables, to allow re-use.
=> pkg/wire: Write* tests

README.md, pkg/nar/fixtures_test.go, pkg/nar/ls/list.go, pkg/nar/reader.go, pkg/nar/reader_test.go, pkg/nar/types.go, pkg/nar/writer.go, pkg/nar/writer_test.go, pkg/wire/bytes_writer.go, pkg/wire/write_test.go
This introduces the writer component for `pkg/nar`, with a similar interface to `archive/tar`.
It also increases test coverage for the NAR reader, thanks to some of the fixtures created for the NAR writer tests.
There's probably some more places where we could have more test coverage, mostly premature closing of the NAR readers and writers, but this can be done as a follow-up.
=> feat(pkg/nar): introduce NAR writer

pkg/nar/header.go, pkg/nar/header_test.go, pkg/nar/ls/list.go, pkg/nar/ls/list_test.go, pkg/nar/reader.go, pkg/nar/types.go, pkg/nar/util.go, pkg/nar/writer.go, pkg/nar/writer_test.go
Nix paths have much stronger requirements than regular paths. The only
thing we don't want to see is a / in the node name.
cc: @puckipedia
=> fix(pkg/nar): loosen node name restrictions

.gitignore, README.md, cmd/gonix/main.go, cmd/gonix/nar/cat.go, cmd/gonix/nar/cmd.go, cmd/gonix/nar/dump.go, cmd/gonix/nar/ls.go, go.mod, go.sum, pkg/nar/dump.go, pkg/nar/dump_test.go, pkg/nar/header.go, pkg/nar/writer.go, pkg/nar/writer_test.go
This introduces a CLI endpoint, exposing some of the functionality
provided inside pkg/.
Right now, it only exposes the functionality provided by the `nix nar
{cat,dump-path,ls}` commands in Nix, but its structure makes adding more
commands easy.
The logic used in the `nar dump-path` command was generic enough to be
moved to `pkg/nar`, and some tests were added.
`pkg/nar/header.go` received some love, and is now using less hardcoded
magic numbers. The `pkg/nar.Header`'s `FileInfo().Mode()` is getting used
to render the permission string in the `nar ls` subcommand.
=> Introduce cmd/gonix, pkg/nar.DumpPath

cmd/gonix/nar/cat.go, cmd/gonix/nar/ls.go, pkg/nar/dump.go, pkg/nar/dump_test.go, pkg/nar/header.go, pkg/nar/header_test.go, pkg/nar/reader.go, pkg/nar/reader_test.go, pkg/nar/writer.go, pkg/nar/writer_test.go
This has confused at least two people.
This will bring the `gonix` CLI a bit more in line with how Nix behaves, gets rid of the ugly `.` when printing the root of a NAR.
cc @manveru
=> feat(pkg/nar): show a leading slash

.github/workflows/golangci-lint.yml
It currently panic()'s ( https://github.com/golangci/golangci-lint-action/issues/440 ).
=> .github/workflows: Bump golangci-lint action

pkg/derivation/derivation.go, pkg/derivation/derivation_test.go
That outputs the default output path, much like Nix string interpolation does.
Suggested by @jfroche in https://github.com/nix-community/go-nix/pull/38#issuecomment-1114051028.
=> pkg/derivation: Implement String method

pkg/nar/fixtures_test.go, pkg/nar/reader.go, pkg/nar/reader_test.go
Fail if a NAR file is passed that contains elements in the wrong order.
Elements in NAR files need to be lexicographically ordered for
reproducibility.
=> pkg/nar/reader.go: ensure NAR files are properly ordered

pkg/nar/reader.go, pkg/nar/util.go, pkg/nar/util_test.go, pkg/nar/writer.go, pkg/nar/writer_test.go
The current implementation breaks when the string representation for
the _full path_ is not lexicographically ordered.
This breaks when two nested directories share a prefix such as:
- /cmd/structlayout/main.go
- /cmd/structlayout-optimize
The full path for these strings is not in correct lexicographical
order, but each component is.
=> pkg/nar/writer: Compare order of NAR members correctly

pkg/nar/writer.go
This is a super minor optimisation. An empty struct takes no memory.
=> pkg/nar/writer: Use empty struct instead of interface for channel

pkg/nar/dump.go, pkg/nar/dump_test.go, pkg/nar/header.go, pkg/nar/types.go
This function adds source filtering capabilities to DumpPath.
The interface of this mimics the behaviour of the Nix builtin filterSource.
=> pkg/nar: Add DumpPathFilter

pkg/derivation/derivation.go, pkg/derivation/derivation_test.go
This is the name of the output. It might be the contents of some
structure, but actually calling this struct attribute `Name` makes much
more sense.
=> pkg/derivation: rename Output.Content to Output.Name

pkg/derivation/derivation.go, pkg/derivation/derivation_test.go, pkg/derivation/encode.go, pkg/derivation/parser.go
A lot of the struct structure has been designed to work with the parser
generator we used.
Since https://github.com/nix-community/go-nix/pull/55 we have our own parser, so we can be a bit more flexible with
how the structure of the Derivation struct looks like.
Use the structure that's exposed when invoking `nix show-derivation`,
and peeking at the JSON there.
Outputs, InputDerivations and Env are maps, not lists with odd order
requirements. The Parser takes care of ensuring the order was correct
when parsing it in, and the encoder outputs them in the way things
should be sorted.
This makes the Validate() method much smaller, as there's simply less
invalid states someone manually populating the struct could produce.
=> pkg/derivation: align Derivation struct with json format

pkg/derivation/derivation_test.go, pkg/derivation/drvpath.go, pkg/hash/util.go
This returns the path of a Drv, just by looking at its structure.
=> pkg/derivation: add DrvPath() function

README.md, pkg/nixpath/references/refs.go, pkg/nixpath/references/refs_test.go
This is largely a port of the algorithm that Nix uses but adapted to work with streaming data of unbounded length.
=> pkg/nixpath/references: Add a build output reference scanner

.gitattributes, pkg/derivation/derivation.go, pkg/derivation/json_test.go, pkg/derivation/output.go, pkg/derivation/parser.go, test/testdata/0hm2f1psjpcwg8fijsmr4wwxrx59s092-bar.drv.json, test/testdata/4wvvbi4jwn0prsdxb7vs673qa5h9gr7x-foo.drv.json, test/testdata/build_fixtures.sh, test/testdata/derivation_sha1.nix, test/testdata/derivation_sha256.nix
Committing the original nix source files will allow reproducing test
fixtures both with Nix, as well as eventually our own implementation,
providing a nice closed loop.
This also fixes JSON serialization to match the output of `nix show-derivation`, and adds a test for it.
=> test/testdata: document how fixtures are produced, fix json serialization

cmd/gonix/drv/cmd.go, cmd/gonix/drv_store_uri_mapper.go, cmd/gonix/main.go, pkg/derivation/store/filesystem.go, pkg/derivation/store/filesystem_test.go, pkg/derivation/store/http.go, pkg/derivation/store/uri.go
~This depends on https://github.com/nix-community/go-nix/pull/64 and should be rebased once merged.~ Part of this was already in #58, but excluded from #63.
It introduces `pkg/derivation/store.{HTTPStore,FSStore}`, a `store.NewFromURI` method, and a `gonix drv --drv-store=uri-goes-here show /nix/store/drv-path.drv` command.
`{HTTPStore,FSStore}` don't implement any checking of output paths and referred derivations to exist, but I intend to provide this functionality via some "proxy store", that can be used to cache "remote" `derivation.Store` into a local one, and rely on the local store checks (left as a followup)
=> pkg/derivation/store: add HTTPStore, FSStore, CLI tooling

.gitattributes, pkg/derivation/derivation_test.go, pkg/derivation/parser.go, test/testdata/52a9id8hx688hvlnz4d1n25ml1jdykz0-unicode.drv, test/testdata/52a9id8hx688hvlnz4d1n25ml1jdykz0-unicode.drv.json, test/testdata/cp1252.nix, test/testdata/latin1.nix, test/testdata/m1vfixn8iprlf0v9abmlrz7mjw1xj8kp-cp1252.drv, test/testdata/m1vfixn8iprlf0v9abmlrz7mjw1xj8kp-cp1252.drv.json, test/testdata/unicode.nix, test/testdata/x6p0hg79i3wg0kkv7699935f7rrj9jf3-latin1.drv, test/testdata/x6p0hg79i3wg0kkv7699935f7rrj9jf3-latin1.drv.json
This ensures no copying.
The following test program:
``` go
package main
import (
"bytes"
"fmt"
"io"
"os"
"testing"
"time"
"github.com/nix-community/go-nix/pkg/derivation"
)
func main() {
drvPath := "/nix/store/lfb109iifgph2xa94aps13n2w8bpbqsq-texlive-combined-full-2021-final.drv"
n := 50
derivationFile, err := os.Open(drvPath)
if err != nil {
panic(err)
}
drvBytes, err := io.ReadAll(derivationFile)
if err != nil {
panic(err)
}
{
start := time.Now()
for i := 0; i < n; i++ {
_, err := derivation.ReadDerivation(bytes.NewReader(drvBytes))
if err != nil {
panic(err)
}
}
fmt.Println(time.Since(start) / time.Duration(n))
}
fmt.Println("Allocs:", int(testing.AllocsPerRun(n, func() {
_, err := derivation.ReadDerivation(bytes.NewReader(drvBytes))
if err != nil {
panic(err)
}
})))
}
```
Yields …
=> pkg/derivation: Use unsafe to cast from []byte to string

pkg/derivation/derivation.go, pkg/derivation/output.go, pkg/nixbase32/nixbase32.go, pkg/nixbase32/nixbase32_test.go, pkg/nixpath/nixpath.go, pkg/nixpath/nixpath_test.go
This is a follow-up to https://github.com/nix-community/go-nix/pull/77.
This ensures we don't have to do costly allocations for every store path that we validate when validating a derivation.
The following test program:
``` go
package main
import (
"bytes"
"fmt"
"io"
"os"
"testing"
"time"
"github.com/nix-community/go-nix/pkg/derivation"
)
func main() {
drvPath := "/nix/store/lfb109iifgph2xa94aps13n2w8bpbqsq-texlive-combined-full-2021-final.drv"
n := 50
derivationFile, err := os.Open(drvPath)
if err != nil {
panic(err)
}
drvBytes, err := io.ReadAll(derivationFile)
if err != nil {
panic(err)
}
{
start := time.Now()
for i := 0; i < n; i++ {
_, err := derivation.ReadDerivation(bytes.NewReader(drvBytes))
if err != nil {
panic(err)
}
}
fmt.Println(time.Since(start) / time.Duration(n))
} …
```
=> pkg/nixpath: Reduce allocations when validating

pkg/nar/dump.go, pkg/nar/dump_nonwindows_test.go, pkg/nar/header.go, pkg/nar/header_mode.go, pkg/nar/header_mode_windows.go, pkg/nar/types.go
Simply return an error when stumbling over something unknown during
DumpPath.
=> pkg/nar: drop TypeUnknown

pkg/nixpath/nixpath.go
The hash part of a nixpath can only contain letters part of the
nixbase32 alphabet.
=> pkg/nixpath/nixpath.go: be more strict in PathRe

pkg/narinfo/signature/public_key.go, pkg/narinfo/signature/signature.go
This makes it easier to access them from the outside, which is useful when transforming into another data structure.
=> pkg/narinfo/signature: export Name and Data fields

cmd/gonix/drv/cmd.go, go.mod, go.sum, pkg/derivation/json_test.go, test/testdata/0hm2f1psjpcwg8fijsmr4wwxrx59s092-bar.drv.json, test/testdata/292w8yzv5nn7nhdpxcs8b7vby2p27s09-nested-json.drv.json, test/testdata/4wvvbi4jwn0prsdxb7vs673qa5h9gr7x-foo.drv.json, test/testdata/9lj1lkjm2ag622mh4h9rpy6j607an8g2-structured-attrs.drv.json, test/testdata/ch49594n9avinrf8ip0aslidkc4lxkqv-foo.drv.json, test/testdata/h32dahq0bx5rp1krcdx3a53asj21jvhk-has-multi-out.drv.json, test/testdata/ss2p4wmxijn652haqyd7dckxwl4c7hxx-bar.drv.json
It looks like the keys in `nix show-derivation` output were not sorted (but stable), and some Nix version update changed that.
Regenerate the JSON files to prevent CI from failing.
=> test/testdata: regenerate JSON files

pkg/derivation/drv_path.go
This documents in greater detail how exactly a .drv path is constructed.
=> pkg/derivation/drv_path.go: document .drv path construction better

pkg/derivation/derivation.go
This fix makes sure to start checking with the first element (instead of the second).
cc @adisbladis
=> fix validation of sorted elements in list

.github/workflows/ci.yml, .github/workflows/golangci-lint.yml, .golangci.yml, pkg/derivation/store/badger.go, pkg/derivation/store/filesystem.go, pkg/derivation/store/http.go, pkg/derivation/store/map.go
It seems the output has changed recently. Pin the version of Nix to prevent CI from failing unrelatedly.
Also, bump the golangci-lint version we're using and address some of the new warnings.
=> GH actions: pin Nix version in fixture test

README.md, pkg/derivation/derivation.go, pkg/derivation/derivation_test.go, pkg/derivation/drv_path.go, pkg/derivation/hashes.go, pkg/derivation/output.go, pkg/derivation/store/filesystem.go, pkg/derivation/store/filesystem_test.go, pkg/derivation/store/http.go, pkg/derivation/store/store_test.go, pkg/narinfo/check.go, pkg/narinfo/fingerprint.go, pkg/nixpath/nixpath.go, pkg/nixpath/nixpath_test.go, pkg/storepath/references/refs.go, pkg/storepath/references/refs_test.go, pkg/storepath/storepath.go, pkg/storepath/storepath_test.go
The whole module layout was a bit messy - store paths had to be passed in primarily with the store dir prefix, even though it's not possible to have a different prefix, at least with the way it's currently structured.
There were Absolute() helper functions which helped with concatenation of strings, but no actual validation, which also were not really used outside of tests. The comments were also wrong, as no cleaning of store paths actually did happen.
Some library code (like pkg/derivation) even started implementing their own String() methods.
Clean this up a bit - have NixPath's FromString() receive a non-absolute path, and have an additional FromAbsolutePath() method that can be used if you have an absolute path.
Move from nixpath.Absolute() to a Absolute() function defined on a …
=> pkg/nixpath: move to pkg/storepath, make FromString receive non-absolute paths

pkg/hash/encode.go, pkg/hash/from.go, pkg/hash/parser.go
This allows creating a Hash from a hashType and digest.
We don't populate unused h.hash anymore, as ParseNixBase32 now uses FromHashTypeAndDigest too, and the size checks are done there.
cc @lheckemann
=> pkg/hash: add FromHashTypeAndDigest function

pkg/narinfo/check.go, pkg/narinfo/narinfo_test.go
The deriver field is optional so the `Check()` function should not return an error if it's empty.
References:
- [nix-serve source code](https://github.com/edolstra/nix-serve/blob/2641d7f6372572f82f8701f38c8cd5aaed0188b4/nix-serve.psgi#L37).
- [narinfo rust crate](https://docs.rs/narinfo/latest/narinfo/struct.NarInfo.html#structfield.deriver)
ref https://github.com/kalbasit/ncps/issues/51
=> narinfo: Deriver is optional, Check must not fail if empty

pkg/nixbase32/nixbase32.go, pkg/nixbase32/nixbase32_test.go
I spent some time fuzzing the nixbase32 and discovered that under some conditions (`enc = "0"`), the `DecodeString` can panic; returning an error is better-suited in this case.
=> fix(nixbase32): do not panic for invalid encoding

pkg/narinfo/narinfo_test.go, pkg/narinfo/parser.go
Some cache servers return `Deriver: unknown-deriver` which breaks verification of a narinfo. Treat such deriver as if no deriver was given at all.
ref https://github.com/kalbasit/ncps/issues/171
=> fix(pkg/narinfo): Treat unknown-deriver as no deriver
